name       : cdemu-client
version    : 3.2.0
release    : 3
source     :
    - https://sourceforge.net/projects/cdemu/files/cdemu-client/cdemu-client-3.2.0.tar.bz2 : a9fea8c54433b6827ea23e13cb10b931609854370afd99a69bea8a750f4a9fff
license    : GPL-2.0-or-later
component  : system.utils
summary    : Command line client for CDEmu Daemon
description: |
    This is cdemu-client, a simple command-line client for controlling CDEmu daemon.
    It is part of the userspace-cdemu suite, a free, GPL CD/DVD-ROM device emulator
    for linux.

    It provides a way to perform the key tasks related to controlling the CDEmu
    daemon, such as loading and unloading devices, displaying devices' status and
    retrieving/setting devices' debug masks.
builddeps  :
    - pkgconfig(glib-2.0)
rundeps    :
    - cdemu-daemon
    - python3-gobject
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install