name       : cdemu-client
version    : 3.2.1
release    : 4
source     :
    - https://datapacket.dl.sourceforge.net/project/cdemu/cdemu-client/cdemu-client-3.2.1.tar.bz2 : e54d2f5686d27bd49e65b84542fb2446ef349c27fa17ee14675d98bd311115b5
license    : GPL-2.0-or-later
component  : system.utils
summary    : Command line client for CDEmu Daemon
description: |
    This is cdemu-client, a simple command-line client for controlling CDEmu daemon.
    It is part of the userspace-cdemu suite, a free, GPL CD/DVD-ROM device emulator
    for linux.

    It provides a way to perform the key tasks related to controlling the CDEmu
    daemon, such as loading and unloading devices, displaying devices' status and
    retrieving/setting devices' debug masks.
rundeps    :
    - cdemu-daemon
    - python3-gobject
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
