name       : cdemu-client
version    : 3.2.5
release    : 10
source     :
    - https://sourceforge.net/projects/cdemu/files/cdemu-client/cdemu-client-3.2.5.tar.xz/download : a72d85eb5bfcbced0108cd7c1827e50220f8f1d7998db30ceb0aa808366c39df
license    : GPL-2.0-or-later
component  : system.utils
summary    : Command line client for CDEmu Daemon
description: |
    This is cdemu-client, a simple command-line client for controlling CDEmu daemon.
    It is part of the userspace-cdemu suite, a free, GPL CD/DVD-ROM device emulator
    for linux.

    It provides a way to perform the key tasks related to controlling the CDEmu
    daemon, such as loading and unloading devices, displaying devices' status and
    retrieving/setting devices' debug masks.
rundeps    :
    - cdemu-daemon
    - python-gobject
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
