name       : cdemu-client
version    : 3.0.4
release    : 1
source     :
    - https://sourceforge.net/projects/cdemu/files/cdemu-client/cdemu-client-3.0.4.tar.bz2 : e415a98672ac1ed908dab2ba43a94bc0af7653c470a87d6d9338a59d9856fd86
license    : GPL-2.0
component  : system.utils
summary    : Command line client for CDEmu Daemon
description: |
    This is cdemu-client, a simple command-line client for controlling CDEmu daemon.
    It is part of the userspace-cdemu suite, a free, GPL CD/DVD-ROM device emulator
    for linux.
    
    It provides a way to perform the key tasks related to controlling the CDEmu
    daemon, such as loading and unloading devices, displaying devices' status and
    retrieving/setting devices' debug masks.
builddeps  :
    - pkgconfig(glib-2.0)
rundeps    :
    - cdemu-daemon
    - python-gobject
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    install -D -d -m 00755 $installdir/usr/share/bash-completion/completions
    install -m 00644 $installdir/etc/bash_completion.d/* $installdir/usr/share/bash-completion/completions/.
    rm -rf $installdir/etc
