name       : cdemu-client
version    : 3.2.3
release    : 5
source     :
    - https://sourceforge.net/projects/cdemu/files/cdemu-client/cdemu-client-3.2.3.tar.bz2/download : f883800db99d39a91f41b94ede7c799c12318f15f4c138eeca0374374c156caf
license    : GPL-2.0-or-later
component  : system.utils
summary    : Command line client for CDEmu Daemon
description: |
    This is cdemu-client, a simple command-line client for controlling CDEmu daemon.
    It is part of the userspace-cdemu suite, a free, GPL CD/DVD-ROM device emulator
    for linux.

    It provides a way to perform the key tasks related to controlling the CDEmu
    daemon, such as loading and unloading devices, displaying devices' status and
    retrieving/setting devices' debug masks.
rundeps    :
    - cdemu-daemon
    - python3-gobject
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
